server:
  port: 8080
  # X-Forwarded-For Header가 존재할 경우 적용 => ServletUriComponentsBuilder.fromCurrentContextPath()
  forward-headers-strategy: native

spring:
  config:
    use-legacy-processing: true # allow "application-{profile}.yml" way
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
